import { Injectable } from '@nestjs/common';

import { TravelState } from '../graph/travel.state';

import { TripPlan, TripPlanResponse, TripMapDay, TripMapStop } from '../models/trip-response.model';

import { BudgetBreakdown } from '../models/budget.model';

import { ActivityCandidate } from '../models/activity-planning.model';
@Injectable()
export class TripPlanAssembler {
  assemble(
    state: TravelState,
  ): TripPlanResponse {
    const request = state.tripRequest!;
    const itinerary = state.itinerary;
    const recommendation =
      state.recommendation;

    /*
     * Phase 2F.5
     *
     * TripFeasibilityNode recalculates the
     * final budget after itinerary generation.
     *
     * Therefore TravelState is now the
     * authoritative source for the final
     * budget and feasibility result.
     */
    const budget: BudgetBreakdown | null =
      state.budgetBreakdown ?? null;
    const tripFeasibility =
      state.tripFeasibility ?? null;

    const days = Math.max(
      state.days ??
      request.durationDays ??
      1,
      1,
    );

    const nights =
      this.calculateNights(
        state,
        days,
      );

    const currency =
      request.budget?.currency ??
      budget?.currency ??
      'USD';

    /*
     * Warnings
     */
    const warnings = [
      ...(request.missingFields.length > 0
        ? request.missingFields.map(
          (field) =>
            `Missing required field: ${field}.`,
        )
        : []),

      ...(budget?.warnings ?? []),

      ...(tripFeasibility?.warnings ??
        []),

      ...(state.flightRanking
        ?.warnings ?? []),

      ...(state.hotelRanking
        ?.warnings ?? []),
    ];

    if (
      !recommendation?.recommendedFlight
    ) {
      warnings.push(
        'No recommended flight is available for the current search.',
      );
    }

    if (
      !recommendation?.recommendedHotel
    ) {
      warnings.push(
        'No recommended hotel is available for the current search.',
      );
    }

    if (!itinerary) {
      warnings.push(
        'The itinerary generator did not return a result. A deterministic fallback was not available.',
      );
    }

    /*
     * Assumptions
     */
    const assumptions = [
      ...request.assumptions,
    ];

    if (
      request.dates.source ===
      'missing'
    ) {
      assumptions.push(
        'Exact travel dates were not provided. The plan will use flexible dates.',
      );
    }

    if (
      request.dates.source ===
      'flexible-window' &&
      request.dates.searchWindow
    ) {
      assumptions.push(
        `Flexible date search window: ${request.dates.searchWindow.startDate} to ${request.dates.searchWindow.endDate}.`,
      );
    }

    /*
     * Include feasibility assumptions
     * generated by TripFeasibilityService.
     */
    if (
      tripFeasibility?.assumptions
    ) {
      assumptions.push(
        ...tripFeasibility.assumptions,
      );
    }

    /*
     * Build deterministic executive summary.
     *
     * This uses the final itinerary and
     * authoritative final budget.
     */
    const executiveSummary =
      this.buildExecutiveSummary(
        state,
        itinerary,
        budget,
        days,
        nights,
        currency,
      );

    /*
     * Final frontend-ready TripPlan.
     */
    const plan: TripPlan = {
      id: this.createPlanId(state),

      status:
        itinerary
          ? 'ready'
          : 'partial',

      request,

      dates: {
        startDate:
          state.startDate,

        endDate:
          state.endDate,

        days,

        nights,

        flexible:
          request.dates.flexible,

        source:
          request.dates.source ??
          'missing',

        searchWindow:
          request.dates.searchWindow,

        assumptions,
      },

      summary: {
        destination:
          state.destination ??
          request.destination ??
          '',

        origin:
          state.origin ??
          request.origin ??
          '',

        travelers:
          state.travelers ??
          request.travelers.total,

        days,

        nights,

        travelStyle:
          state.travelStyle ??
          request.travelStyle,

        budget:
          request.budget?.amount,

        currency,

        summary:
          executiveSummary,
      },

      /*
       * Recommendations
       */
      recommendedFlight:
        recommendation
          ?.recommendedFlight ??
        null,

      availableFlights:
        state.flights,

      recommendedHotel:
        recommendation
          ?.recommendedHotel ??
        null,

      availableHotels:
        state.hotels,

      flightAlternatives:
        recommendation
          ?.flightAlternatives ??
        [],

      hotelAlternatives:
        recommendation
          ?.hotelAlternatives ??
        [],

      flightRanking:
        state.flightRanking ??
        null,

      hotelRanking:
        state.hotelRanking ??
        null,

      /*
       * Final budget generated by
       * TripFeasibilityNode.
       */
      budget,

      /*
       * Explicit feasibility result.
       */
      tripFeasibility,

      totalEstimatedCost:
        itinerary?.totalEstimatedCost ??
        (
          budget
            ? `${budget.total} ${currency}`
            : ''
        ),

      /*
       * Itinerary
       */
      itinerary: {
        days:
          itinerary?.dailyPlans ??
          [],
      },

      /*
       * Map
       */
      map:
        this.buildMap(state),

      /*
       * Optimization data
       */
      optimization: {
        flight: {
          recommended:
            recommendation
              ?.recommendedFlight ??
            null,

          cheapest:
            state.flightRanking
              ?.cheapest ??
            null,

          fastest:
            state.flightRanking
              ?.fastest ??
            null,

          fewestStops:
            state.flightRanking
              ?.fewestStops ??
            null,

          lowestEmissions:
            state.flightRanking
              ?.lowestEmissions ??
            null,
        },

        hotel: {
          recommended:
            recommendation
              ?.recommendedHotel ??
            null,

          cheapest:
            state.hotelRanking
              ?.cheapest ??
            null,

          bestRated:
            state.hotelRanking
              ?.bestRated ??
            null,

          bestLocation:
            state.hotelRanking
              ?.bestLocation ??
            null,

          bestForCouples:
            state.hotelRanking
              ?.bestForCouples ??
            null,

          bestForFamilies:
            state.hotelRanking
              ?.bestForFamilies ??
            null,
        },

        budgetFit: {
          requestedBudget:
            request.budget
              ?.amount ??
            null,

          currency,

          estimatedTotal:
            tripFeasibility
              ?.estimatedTotal ??
            budget?.total ??
            null,

          remaining:
            tripFeasibility
              ?.remaining ??
            budget?.remaining ??
            null,

          status:
            tripFeasibility
              ?.status ??
            budget?.status ??
            'no-budget',
        },
      },

      // /*
      //  * Human-readable explanations
      //  */
      // explanations: {
      //   flight:
      //     itinerary
      //       ?.flightRecommendationReason ??
      //     'No flight explanation is available yet.',

      //   hotel:
      //     itinerary
      //       ?.hotelRecommendationReason ??
      //     'No hotel explanation is available yet.',
      // },

      /*
 * ---------------------------------------------------------
 * Recommendation explanations
 * ---------------------------------------------------------
 */
      explanations: {
        flight:
          itinerary
            ?.flightRecommendationReason ??
          'No flight explanation is available yet.',

        hotel:
          itinerary
            ?.hotelRecommendationReason ??
          recommendation?.hotelExplanation?.reason ??
          'No hotel explanation is available yet.',
      },

      hotelExplanation:
        recommendation?.hotelExplanation ?? null,

      // /*
      //  * Booking tips
      //  */
      // bookingTips: {
      //   flight:
      //     itinerary
      //       ?.flightBookingTips ??
      //     [],

      //   hotel:
      //     itinerary
      //       ?.hotelBookingTips ??
      //     [],
      // },

      /*
       * Travel tips
       */
      travelTips:
        itinerary?.travelTips ??
        [],

      /*
       * Final assumptions and warnings
       */
      assumptions,

      warnings:
        this.unique(warnings),
    };

    return {
      success: true,
      trip: plan,
    };
  }

  /*
   * =====================================================
   * EXECUTIVE SUMMARY
   * =====================================================
   */

  private buildExecutiveSummary(
    state: TravelState,
    itinerary: TravelState['itinerary'],
    budget: BudgetBreakdown | null,
    days: number,
    nights: number,
    currency: string,
  ): string {
    const destination =
      state.destination ??
      state.tripRequest?.destination ??
      'your destination';

    const origin =
      state.origin ??
      state.tripRequest?.origin ??
      'your origin';

    const travelers = Math.max(
      state.travelers ??
      state.tripRequest?.travelers?.total ??
      1,
      1,
    );

    const activityCount =
      itinerary?.dailyPlans?.reduce(
        (total, day) =>
          total + (day.activities?.length ?? 0),
        0,
      ) ?? 0;

    const total =
      typeof budget?.total === 'number'
        ? budget.total
        : null;

    const requestedBudget =
      state.tripRequest?.budget?.amount ??
      budget?.budget ??
      null;

    const remaining =
      typeof budget?.remaining === 'number'
        ? budget.remaining
        : null;

    /*
     * ---------------------------------------------------
     * 1. Date context
     * ---------------------------------------------------
     */

    const dateRange =
      state.startDate &&
        state.endDate
        ? `${this.formatDate(
          state.startDate,
        )} to ${this.formatDate(
          state.endDate,
        )}`
        : null;

    /*
     * ---------------------------------------------------
     * 2. Traveler wording
     * ---------------------------------------------------
     */

    const travelerText =
      travelers === 1
        ? 'solo traveler'
        : `${travelers} travelers`;

    /*
     * ---------------------------------------------------
     * 3. Actual itinerary geography
     * ---------------------------------------------------
     */

    const areaCounts = new Map<
      string,
      number
    >();

    for (
      const day of itinerary?.dailyPlans ?? []
    ) {
      for (
        const activity of day.activities ?? []
      ) {
        const area =
          activity.area?.trim() ||
          activity.location?.trim();

        if (!area) continue;

        areaCounts.set(
          area,
          (areaCounts.get(area) ?? 0) + 1,
        );
      }
    }

    const topAreas = Array.from(
      areaCounts.entries(),
    )
      .sort((a, b) => b[1] - a[1])
      .slice(0, 3)
      .map(([area]) => area);

    /*
     * ---------------------------------------------------
     * 4. Actual activity categories
     * ---------------------------------------------------
     */

    const categoryCounts = new Map<
      string,
      number
    >();

    for (
      const day of itinerary?.dailyPlans ?? []
    ) {
      for (
        const activity of day.activities ?? []
      ) {
        const category =
          activity.category?.trim();

        if (!category) continue;

        categoryCounts.set(
          category,
          (categoryCounts.get(category) ?? 0) +
          1,
        );
      }
    }

    const topCategory =
      Array.from(categoryCounts.entries()).sort(
        (a, b) => b[1] - a[1],
      )[0]?.[0];

    /*
     * ---------------------------------------------------
     * 5. Largest actual expense
     * ---------------------------------------------------
     */

    const largestExpense =
      this.getLargestExpense(budget);

    /*
     * ---------------------------------------------------
     * 6. Selected recommendations
     * ---------------------------------------------------
     */

    const flight =
      state.recommendation
        ?.recommendedFlight;

    const hotel =
      state.recommendation
        ?.recommendedHotel;

    /*
     * ---------------------------------------------------
     * 7. Opening sentence
     *
     * Make this read like a travel dossier rather
     * than a database description.
     * ---------------------------------------------------
     */

    let summary = '';

    if (dateRange) {
      summary =
        `Your ${days}-day ${destination} trip from ${origin} runs ${dateRange} for ${travelerText}, with ${activityCount} planned stops shaping the itinerary.`;
    } else {
      summary =
        `Your ${days}-day ${destination} trip from ${origin} is built for ${travelerText}, with ${activityCount} planned stops across the itinerary.`;
    }

    /*
     * ---------------------------------------------------
     * 8. Budget insight
     * ---------------------------------------------------
     */

    if (
      total !== null &&
      requestedBudget !== null &&
      remaining !== null
    ) {
      if (remaining > 0) {
        const utilization =
          requestedBudget > 0
            ? Math.round(
              (total / requestedBudget) * 100,
            )
            : null;

        if (
          utilization !== null &&
          utilization <= 85
        ) {
          summary +=
            ` At ${this.formatMoney(
              total,
              currency,
            )} against a ${this.formatMoney(
              requestedBudget,
              currency,
            )} cap, the plan keeps ${this.formatMoney(
              remaining,
              currency,
            )} available for food, shopping, or an extra experience.`;
        } else {
          summary +=
            ` At ${this.formatMoney(
              total,
              currency,
            )} against a ${this.formatMoney(
              requestedBudget,
              currency,
            )} cap, the plan keeps ${this.formatMoney(
              remaining,
              currency,
            )} available for the rest of the trip.`;
        }
      } else if (remaining === 0) {
        summary +=
          ` The estimated cost reaches your ${this.formatMoney(
            requestedBudget,
            currency,
          )} budget exactly, leaving no planned headroom.`;
      } else {
        summary +=
          ` At ${this.formatMoney(
            total,
            currency,
          )}, the current plan exceeds your ${this.formatMoney(
            requestedBudget,
            currency,
          )} budget by ${this.formatMoney(
            Math.abs(remaining),
            currency,
          )}.`;
      }
    } else if (total !== null) {
      summary +=
        ` The current itinerary is estimated at ${this.formatMoney(
          total,
          currency,
        )}.`;
    }

    /*
     * ---------------------------------------------------
     * 9. Geography insight
     * ---------------------------------------------------
     */

    if (topAreas.length >= 3) {
      summary +=
        ` The route moves through ${topAreas[0]}, ${topAreas[1]}, and ${topAreas[2]}, giving the trip a broad spread across ${destination}.`;
    } else if (topAreas.length === 2) {
      summary +=
        ` The itinerary is centered around ${topAreas[0]} and ${topAreas[1]}.`;
    } else if (topAreas.length === 1) {
      summary +=
        ` Most planned stops are concentrated around ${topAreas[0]}.`;
    }

    /*
     * ---------------------------------------------------
     * 10. Largest expense insight
     * ---------------------------------------------------
     */

    if (largestExpense) {
      const expenseLabel =
        this.capitalize(
          largestExpense,
        );

      if (
        total !== null &&
        requestedBudget !== null &&
        requestedBudget > 0
      ) {
        const percentage =
          Math.round(
            (total / requestedBudget) * 100,
          );

        if (largestExpense === 'flights') {
          summary +=
            ` Flights are the largest planned expense, accounting for the biggest fixed cost in the current budget.`;
        } else if (
          largestExpense === 'hotel'
        ) {
          summary +=
            ` Accommodation is the largest planned expense, making the selected stay the main recurring cost in the trip budget.`;
        } else if (
          largestExpense === 'activities'
        ) {
          summary +=
            ` Activities are the largest variable expense, so the experience-heavy itinerary is driving much of the remaining spend.`;
        } else if (
          largestExpense === 'food'
        ) {
          summary +=
            ` Food is the largest variable expense, making meal choices the clearest area to adjust if you want more budget flexibility.`;
        } else {
          summary +=
            ` ${expenseLabel} is the largest planned expense in the current ${percentage}% budget utilization.`;
        }
      } else {
        summary +=
          ` ${expenseLabel} is the largest planned expense in the current itinerary.`;
      }
    }

    /*
     * ---------------------------------------------------
     * 11. Trip character
     *
     * Derive this from actual itinerary data instead
     * of adding generic marketing language.
     * ---------------------------------------------------
     */

    if (topCategory) {
      const categoryDescriptions: Record<
        string,
        string
      > = {
        attraction:
          'The plan leans toward major attractions and landmarks.',
        culture:
          'The itinerary has a strong cultural focus.',
        nature:
          'Outdoor and nature experiences form a noticeable part of the route.',
        shopping:
          'Shopping is a meaningful part of the planned experience.',
        food:
          'Food experiences play a central role in the itinerary.',
        nightlife:
          'The itinerary has a clear evening and nightlife component.',
        experience:
          'The plan emphasizes hands-on and experiential activities.',
      };

      const categoryText =
        categoryDescriptions[
        topCategory.toLowerCase()
        ];

      if (categoryText) {
        summary += ` ${categoryText}`;
      }
    }

    /*
     * ---------------------------------------------------
     * 12. Keep the summary compact.
     * ---------------------------------------------------
     */

    return summary.trim();
  }

  private getLargestExpense(
    budget: BudgetBreakdown | null,
  ): string | null {
    if (!budget) {
      return null;
    }

    const categories = [
      'flights',
      'hotel',
      'food',
      'transportation',
      'activities',
      'miscellaneous',
    ] as const;

    let largest:
      | (typeof categories)[number]
      | null = null;

    let largestValue = -Infinity;

    for (const category of categories) {
      const value =
        Number(budget[category]) || 0;

      if (value > largestValue) {
        largestValue = value;
        largest = category;
      }
    }

    return largest;
  }

  private formatMoney(
    value: number,
    currency: string,
  ): string {
    const rounded =
      Math.round(
        value * 100,
      ) / 100;

    return `${currency} ${rounded.toLocaleString(
      'en-US',
    )}`;
  }

  private formatDate(
    value: string,
  ): string {
    const date =
      new Date(
        `${value}T00:00:00Z`,
      );

    if (
      Number.isNaN(
        date.getTime(),
      )
    ) {
      return value;
    }

    return date.toLocaleDateString(
      'en-US',
      {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
        timeZone: 'UTC',
      },
    );
  }

  private capitalize(
    value: string,
  ): string {
    return (
      value.charAt(0).toUpperCase() +
      value.slice(1)
    );
  }

  private buildMap(
    state: TravelState,
  ) {
    const candidateMap =
      new Map<
        string,
        ActivityCandidate
      >();

    for (
      const day of
      state.plannedDayCandidates ??
      []
    ) {
      for (
        const candidate of
        day.activities
      ) {
        candidateMap.set(
          candidate.id,
          candidate,
        );
      }
    }

    const days: TripMapDay[] =
      (
        state.itinerary
          ?.dailyPlans ??
        []
      ).map((day) => {
        const stops: TripMapStop[] =
          day.activities.map(
            (activity) => {
              const candidate =
                activity.id
                  ? candidateMap.get(
                    activity.id,
                  )
                  : undefined;

              return {
                id:
                  activity.id ??
                  candidate?.id,

                title:
                  activity.title,

                location:
                  activity.location,

                latitude:
                  activity.latitude ??
                  candidate?.latitude,

                longitude:
                  activity.longitude ??
                  candidate?.longitude,

                time:
                  activity.time,
              };
            },
          );

        return {
          day: day.day,

          title:
            day.title,

          area:
            state.plannedDayCandidates
              ?.find(
                (item) =>
                  item.day ===
                  day.day,
              )?.area,

          stops,
        };
      });

    return {
      destination:
        state.destination ?? '',

      days,
    };
  }

  private calculateNights(
    state: TravelState,
    days: number,
  ): number {
    if (
      state.startDate &&
      state.endDate
    ) {
      const start =
        new Date(
          `${state.startDate}T00:00:00Z`,
        );

      const end =
        new Date(
          `${state.endDate}T00:00:00Z`,
        );

      const nights = Math.round(
        (
          end.getTime() -
          start.getTime()
        ) / 86400000,
      );

      return Math.max(
        nights,
        0,
      );
    }

    if (
      state.tripRequest
        ?.durationNights != null
    ) {
      return Math.max(
        state.tripRequest
          .durationNights,
        0,
      );
    }

    return Math.max(
      days - 1,
      0,
    );
  }

  private createPlanId(
    state: TravelState,
  ): string {
    const seed = [
      state.origin ?? '',
      state.destination ?? '',
      state.startDate ??
      'flexible',
      state.endDate ?? '',
      state.travelers ?? 0,
      state.message,
    ].join('|');

    let hash = 0;

    for (
      let index = 0;
      index < seed.length;
      index += 1
    ) {
      hash =
        (
          hash * 31 +
          seed.charCodeAt(index)
        ) | 0;
    }

    return `trip_${Math.abs(hash).toString(36)}`;
  }

  private unique(
    values: string[],
  ): string[] {
    return values.filter(
      (
        value,
        index,
      ) =>
        value &&
        values.indexOf(value) ===
        index,
    );
  }
}